{
 "title": "Example dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Current Enrollments",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cash_current_enrollments_count", "legendFormat": "{{ cash_enrollment_state }}" }
   ]
  },
  {
   "title": "Enrolled Sellers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cash_current_enrollments_count", "legendFormat": "{{ cash_enrollment_state }}" }
   ]
  },
  {
   "title": "Days Per Enrollment State",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cash_enrollment_time_spent_per_state",
     "legendFormat": "{{ enrollment_state }}"
    }
   ]
  },
  {
   "title": "Average Days to Complete Enrollment",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cash_enrollment_time_spent_per_state",
     "legendFormat": "{{ enrollment_state }}"
    }
   ]
  },
  {
   "title": "Frequency of Time to Complete Draft Stage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cash_time_spent_per_enrollment_state_in_days_bucket{cash_enrollment_state=\"DRAFT\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}